import{a as P,S as q,i as s}from"./assets/vendor--6n4cVRZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const E="52770413-51c449e2c65101d33f96e6ea5",$="https://pixabay.com/api/",B=15;async function u(r,t){return(await P.get($,{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:i,largeImageURL:c,tags:e,likes:o,views:n,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${n}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${v}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function A(){f.innerHTML=""}function g(){m.classList.remove("is-hidden")}function p(){m.classList.add("is-hidden")}function L(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}const O=document.querySelector(".form"),_=document.querySelector(".load-more");let l="",a=1,d=0;const w=15;O.addEventListener("submit",x);_.addEventListener("click",D);async function x(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),a=1,!l){s.error({message:"Please enter a search term!"});return}A(),b(),g();try{const t=await u(l,a);if(d=t.totalHits,t.hits.length===0){s.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),d<=w?s.info({message:"We're sorry, but you've reached the end of search results."}):L()}catch{s.error({message:"Something went wrong!"})}finally{p()}}async function D(){b(),g();try{a+=1;const r=await u(l,a);y(r.hits),G(),a*w<d?L():s.info({message:"We're sorry, but you've reached the end of search results."})}catch{s.error({message:"Something went wrong. Please try again."})}finally{p()}}function G(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
